### ISSUE TITLE
403 when posting

### ISSUE THREAD

**Issue by JNaftali** [adayoung/ada-pastebin#5]
Hello! First of all, lemme say thanks so much for the site you've made, it's pretty stellar.

Just wanted to let you know that I (and a number of others I've chatted with) have occasionally been getting 403 errors when trying to post. Always been able to get thru in the end by posting via incognito, if that tells you anything.

**Comment by adayoung** [comment]
Yay hi! Oop, I think that's happening because of a stale cookie from the old pastebin application. It works in incognito because that doesn't bring cookies from your existing session. Let me make it use a different cookie so it'll work either way!

**Comment by adayoung** [comment]
@JNaftali Let me know if it keeps happening please!
